import type { Metadata } from "next";
import "./globals.css";
import {Noto_Sans_Lao} from "next/font/google";

const notoSansLao = Noto_Sans_Lao({
  subsets: ["latin"],
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSansLao.className}>
        {children}
      </body>
    </html>
  );
}
